platform :ios, '5.1.1'
xcodeproj 'Coursistant.xcodeproj'
pod 'AFNetworking', '~> 1.3.3'
pod 'AFHTTPRequestOperationLogger', '~> 0.9.0'
pod 'TTTAttributedLabel', '~> 1.6.3'
pod 'AFDownloadRequestOperation', '~> 1.0.0' 
pod 'ZipArchive', '~> 1.2.0'
pod 'Appirater'
pod 'libextobjc/EXTScope'
